# Development frontend: nginx:alpine serving static files + reverse proxy to backend
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf || true
RUN rm -rf /usr/share/nginx/html/*

COPY client/main.html /usr/share/nginx/html/index.html
COPY client/css/ /usr/share/nginx/html/css/
COPY client/js/ /usr/share/nginx/html/js/

COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
