FROM nvidia/cuda:12.1.1-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common curl build-essential

# Add the deadsnakes PPA to access newer Python versions
RUN add-apt-repository ppa:deadsnakes/ppa && apt-get update

# Install Python 3.12 
RUN apt-get install -y python3.12

# Use the curl command to install the latest pip for Python 3.12
RUN curl -O https://bootstrap.pypa.io/get-pip.py && python3.12 get-pip.py

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Set Python 3.12 as the default python3 and python
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1 && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1

# Verify installations
RUN python --version
RUN pip --version
RUN pip install --no-cache-dir --upgrade setuptools

WORKDIR /src

COPY ./requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt 
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cu121

COPY ./api /src/api


RUN useradd --create-home --shell /bin/bash appuser && \
    chown -R appuser:appuser /src
USER appuser

EXPOSE 8000

CMD ["fastapi", "dev", "api/api.py", "--host", "0.0.0.0", "--port", "8000"]
